### ISSUE TITLE
Idea- acknowlegment of an alert 

### ISSUE THREAD

**Issue by xinity** [arachnys/cabot#214]
I've been wondering if it's easy to implement an acknowlegment system so a tech working on a triggered alert can "pause" alert notification for the time he fix the issue. 

We can already disable one or more checks, but i was thinking about something a little bit more easier. 

Any clues maybe ?

**Comment by dbuxton** [comment]
Yes it would be nice to "acknowledge" an alert for a couple of reasons:

* If a `CRITICAL` alert occurs, triggering a phone call, and the primary
responder isn't available for any reason, it would be great to work down
the list of potential responders until someone confirms that they can pick
it up.
* Silence additional notifications (as you suggest)

One thing I'd want to watch out for however is that it continues to be
obvious that an alarm is still going off - perhaps this can be accomplished
by continuing to send alerts but them being at WARNING level or some other
level...

**Comment by xinity** [comment]
Like notification interval we maybe can have a acknowlegment interval which would silence alerts, some square to tick on to enabled the acknowlegment system but would re enable alerts alert when the acknowlegment interval is met, this way we can easily implement sla

**Comment by barakcoh** [comment]
+1

**Comment by xinity** [comment]
here is what we are working on:
if service.STATUS != PASSING then a acknowldegment button will appear next to the failed service in cabot.pushing it will "pause" notification for this service.

a celery tasks will check for how long the alert has been acknowledged, if time between acknowledgment and 'now' is greater than X
then it will trigger another notification and remove the acknowledgment status.

as we are by now, the task doesn't seem to be hard to build, but we will have to update django db model and change a bit the service status page.

**Comment by dbuxton** [comment]
Can't the check for acknowledgement just be part of the alerting logic?

**Comment by xinity** [comment]
@dbuxton I'm not sure to understand :-( would you please explain a bit what you are thinking about?

**Comment by dbuxton** [comment]
can we just add a DateTimeField `alert_acknowledged_at` to the Service model, and as part of the alerting logic (which already checks whether an alert has been sent in the recent past) do something like

    if (timezone.now() - service.alert_acknowledged_at).total_seconds() < ACKNOWLEDGEMENT_SILENCE_DURATION * 60:
        # skip alerting

I'd also suggest having an `alert_acknowledged_by` attribute so that we know who is supposed to be taking care of the alert.

Alternatively we could put in a new `AlertAcknowledgement` model - that would be more powerful in the long run and would give an audit trail, which could be useful.

Does that make sense?

**Comment by xinity** [comment]
Nice!! Indeed I'll what I can achieve ;-) I'll keep in touch asap

**Comment by dbuxton** [comment]
Hi @xinity - because I thought this was a neat idea I had a stab at it - changes have landed in https://github.com/arachnys/cabot/commit/45449861503fdfc3a8dee04180803a3c057c505a

It basically just pauses alerts for a configurable amount of time (20 mins by default) and gives the service page a toggle so you can pause/resume alerts for that service.

![cabot_by_arachnys_-_cloudflare](https://cloud.githubusercontent.com/assets/314113/10242527/acf1efc6-68f1-11e5-944a-48c7fc9fc693.png)

Let me know what you think. It's best (though not necessary) to update plugins to support less intrusive notifications (that essentially say "x is working on it") via the `send_alert_update` method on the plugin - currently https://github.com/bonniejools/cabot-alert-hipchat/commit/5985c5cb55ef0f40df743807726b2411746f7dc8 does at version 1.7.0. (You will have to make sure that is the version being installed...)

**Comment by xinity** [comment]
I'll take a closer this weekend, nice job by the way
