### ISSUE TITLE
[Question] How to configure HTTP-Port?

### ISSUE THREAD

**Issue by christianwedell** [arachnys/cabot#286]
Hello,
I'm running Cabot with nginx on a different Port than 80. Everything works fine, but, when I get an alert notification via Pushover, it doesn't points to the alert correctly.

I tried to set the port with WWW_HTTP_HOST=my.server:xxxx but this doesn't work.
Also setting WWW_PORT=xxxx seems to have no effect.

Any ideas?

**Comment by dbuxton** [comment]
According to https://github.com/packetcollision/cabot-alert-pushover/blob/c10f34e59c9f289e60016e7240c4e6ada611f611/cabot_alert_pushover/models.py#L54 this should work fine.

Possibly some issue with escaping the `:`? (You could try quoting the `WWW_HTTP_HOST` string) - but don't see why that wouldn't work out of the box.

Are you sure that you are updating the config correctly? (In general, you have to redeploy rather than just edit the files in-place because of the way we generate upstart configs as part of deploy process).

**Comment by christianwedell** [comment]
Hello dbuxton,
Quoting made it! Great!
(I always redeploy the config)
Thanks!
