### ISSUE TITLE
Twilio alerts not sending

### ISSUE THREAD

**Issue by jimiguru** [arachnys/cabot#362]
All twilio creds verified and work in other applications.

Nothing in cabot logs indicating failure.  Email alerts work fine. 

Any ideas?

**Comment by bonniejools** [comment]
Twilio phone calls only trigger [when the service is at critical status](https://github.com/cabotapp/cabot-alert-twilio/blob/master/cabot_alert_twilio/models.py#L34). Try increasing the severity of your checks to CRITICAL.

**Comment by jimiguru** [comment]
Hello, thank you for the reply.  The services are all marked critical and no Twilio SMS or Phone calls are being sent.

**Comment by bonniejools** [comment]
The fact that nothing is being sent on either suggests that the problem is not in the plugin itself.

* Check your Twilio usage records to be certain nothing is being sent.
* Are you sure that the users have their mobile phone numbers set.
* Double check the Twilio settings. Make sure you didn't accidentally change the variable names in production.env.

Worst case: Download a copy of the [new and unreleased plugin system](https://github.com/arachnys/cabot/pull/349) and redeploy (this will update your Cabot instance). Go to the 'plugins' page and select 'cabot_alert_twilio' and test from there.
