### ISSUE TITLE
PyPI Release

### ISSUE THREAD

**Issue by ipmb** [arachnys/cabot#44]
As discussed in #41 cabot should be released on PyPI.

**Comment by Duologic** [comment]
For internal projects, I build Python Wheels with compiled static in it, easy to install that way. No more compiling of `.coffee` files and such, no external dependencies.

**Comment by dbuxton** [comment]
@mallniya it has come to our attention that you're the maintainer of https://pypi.python.org/pypi/cabot at the moment - rather than use a confusingly similar name, could you transfer ownership to `arachnys`? (Currently we have uploaded as [cabotapp](https://pypi.python.org/pypi/cabotapp/0.8.3)

(Just need to log in to PyPI and add arachnys as an owner here: https://pypi.python.org/pypi?:action=role_form&package_name=cabot)

Many thanks, apologies for the inconvenience.

**Comment by mallniya** [comment]
sure, @dbuxton, done.

**Comment by dbuxton** [comment]
Much appreciated, thank you very much. 

@frankh can you take care of building releases and uploading them there?

**Comment by frankh** [comment]
@dbuxton done
