### ISSUE TITLE
test phone call works, but no phone call when critical check fails

### ISSUE THREAD

**Issue by hontvari** [arachnys/cabot#518]
I have setup Twillio phone calls and SMS. SMS works as expected, but phone calls do not. In Plugin Settins / Twilio Phone Call / Alert Test Passing->Critical I receive the call. When a service, configured with alert types Twilio Phone Call and Email and a single HTTP check (with Importance: Critical , Active: true), which fails, I do not receive the phone call. Furthermore there is no trace of the call in the logs according to
`docker logs dockercabot_web_1`
There is no Django error notification email and there is nothing in Twilio console about even a failed API call.

**Comment by frankh** [comment]
Hi @hontvari ,

This is likely because phone calls only go to the person "on duty", as opposed to the normal way alerts are sent. You either need to set up a duty roster (with google calendar), or if you edit the user profile in django admin you can set the "Fallback Alert User" option on your user profile

**Comment by hontvari** [comment]
Yes, it started to make phone calls after I navigated to <user name> / Django admin / User profiles - Change / <my user name> and ticked the Fallback alert user check box.

I would like to see an error message in the log (and conseqently a Django error email?) if a critical error happened but no one is on duty, including missing fallback alert user.
