### ISSUE TITLE
JenkinsCheck debounce should mean job failures, not check failures

### ISSUE THREAD

**Issue by JeanFred** [arachnys/cabot#536]
Debounce is “the number of successive failures permitted before check will be marked as failed”. It is very useful to avoid alerts on expected hiccups.

For checks whose retry logic lies in Cabot, by the means of the `frenquency` (which is the case for Graphite checks, HTTP checks and ICMP checks), it makes sense that the debounce is about how often Cabot retried things.

For JenkinsChecks, however, we have no control over how often Cabot checks the job. This means that even a debounce of eg 5 can trigger an alert over 1 job failure.

I propose that `debounce` is repurposed for Jenkins jobs to mean « How many consecutive Jenkins job failures are allowed ». The logic on how often to retry resides in the Jenkins job itself (frequency of the job, auto-retry, delays in auto-retry, etc.).

cc @keot, @frankh @m-brown @MrSaints with whom we discusses this in the past.

Now, we would need to somehow extract/override some of the logic that is in  `models.calculate_debounced_passing` − and in a way that is compatible with the new plugin infrastructure :)

**Comment by MrSaints** [comment]
I agree with this, but:

1.  I also think we need to consider instances where a job has not been running for some time for whatever reason. That is, maybe it is not enough to be checking for consecutive failures, but also for time since last job executed?
2. Would it create confusion if we re-used `debounce`? I am in favour of limiting the meaning of things

**Comment by JeanFred** [comment]
@MrSaints Thanks for your comment

1. Good point. There is already “max queued build time” (“Alert if build queued for more than this many minutes.”), but what you want may be slightly different. Although I could argue that logic should live in Jenkins (ie, if your job is critical, you should have either have an auto-retry on it or a higher cron frequency). What do you think?

2. Not sure. I would argue that the current behaviour is misleading, and that the proposed change aligns more with what would be understood by “debounce”

**Comment by MrSaints** [comment]
@JeanFred 

1. Yea, I understand we have all that. But I was thinking more along the lines of, what happens when the job stops running for whatever reason? Like if it was disabled, and forgotten

2. It is misleading. But my thought is not to re-purpose it, but to get rid of it, and add a new field that aligns more with Jenkins, e.g. consecutive failures, rather than something abstract that behaves differently with Jenkins, and with other checks

**Comment by frankh** [comment]
I'm up for repurposing debounce. In my opinion, it's fixing an existing bug with debounce, as the current behavior is not what you'd expect

**Comment by dbuxton** [comment]
Agree

**Comment by JeanFred** [comment]
Hmmmm, as I was working on this, and fixing more bugs in the Jenkins handling: what to do when Jenkins has a blip and is inaccessible?

Right now, we pass as success. Per #505 we may want to change that.

If we do that, then:
* the debounce will not apply to the Cabot check, and one blip = failure
* if we do implement this, then Cabot would wait for job failures > debounce, which would never happen.

This seems to call for two debounce...

**Comment by JeanFred** [comment]
I have made a first stab in 5ac9c64, but realised the way `recent_results` works would prevent it from working in many cases. Now, we can always mitigate that by returning more results in `recent_results` − but I will try this another way :)
