### ISSUE TITLE
Is docker-compose correct?

### ISSUE THREAD

**Issue by sergeyklay** [arachnys/cabot#648]
I'm not absolutely sure, but it seems that the documentation from the official site is not enough. I've installed docker, docker-compose, cloned this repo and followed the instructions from the official site: https://cabotapp.com/dev/get-started.html

There a tons of errors, warnings, error traces, and fatals. Almost for every service. Please see the log I've attached: [cabot.log](https://github.com/arachnys/cabot/files/2650270/cabot.log).

I deleted all containers, removed all volumes, rebuiled images and started again. The same output.

**Comment by dankonino** [comment]
@sergeyklay I had some issues with this and turned out when just wanted to start it I wasn't using the https://cabotapp.com/qs/quickstart.html right link to the repo which is bit different than in the one hack it yourself 
`git clone git@github.com:cabotapp/docker-cabot.git`
Maybe try that one if you just want to start it?

**Comment by sergeyklay** [comment]
Did you managed successfully start cabot using docker-compose project? I asking because I'm failed, at least a few weeks ago.

**Comment by dankonino** [comment]
@sergeyklay yes I am running it locally for few weeks and recently also on our server :) so feel free to go on with that QuickStart link I sent you

**Comment by sergeyklay** [comment]
Thank you
